### ISSUE TITLE
Typo in main Readme

### ISSUE THREAD

**Issue by brijrajsingh** [Azure-Samples/automated-test-environment-for-aks-applications#4]
### This issue is for a: `Typo in Main readme`
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Main readme - Features section https://github.com/Azure-Samples/automated-test-environment-for-aks-applications#features "Port-Froward" Word typo

### Expected/desired behavior
> Should be "Port-Forward"

**Comment by prabdeb** [comment]
Closed via #5
